version: '3'

# networks:
#   default:
#     external:
#       name: nginx-proxy_default

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx_eazyordering 
    # environment:
    #   LETSENCRYPT_EMAIL: miguekos1233@gmail.com
    #   LETSENCRYPT_HOST: homey.apps.com.pe,www.homey.apps.com.pe
    #   VIRTUAL_HOST: homey.apps.com.pe,www.homey.apps.com.pe
    ports:
      - 8808:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      # - redis
      - mysql
      - mailhog
    

  mysql:
    image: mysql:5.7.29
    container_name: mysql_eazyordering 
    restart: unless-stopped
    tty: true
    ports:
      - 33067:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: common404
      MYSQL_ROOT_PASSWORD: common404
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /usr/local/volumes/mysql_eazyordering:/var/lib/mysql
    

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_eazyordering 
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:rw
    

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer_eazyordering 
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    

  # npm:
  #   image: node:13.7
  #   container_name: npm
  #   volumes:
  #     - ./src:/var/www/html
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   working_dir: /var/www/html
  #   entrypoint: ['npm']
  

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan_eazyordering 
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_eazyordering 
    ports:
      - 1025:1025
      - 8025:8025
    
